





-- 기본값으로 시퀀스 생성  : 이름은 SEQ_TEST

CREATE SEQUENCE SEQ_TEST;

SELECT * FROM USER_SEQUENCES; 

CREATE SEQUENCE SEQ_EMPNO
START WITH 300
INCREMENT BY 5
MAXVALUE 310
NOCYCLE
NOCACHE;


--====================================

--시퀀스사용
 SELECT SEQ_EMPNO.CURRVAL FROM DUAL;
 
 SELECT SEQ_EMPNO.NEXTVAL FROM DUAL;
  SELECT SEQ_EMPNO.CURRVAL FROM DUAL;
  
   SELECT SEQ_EMPNO.NEXTVAL FROM DUAL;
    SELECT SEQ_EMPNO.NEXTVAL FROM DUAL;
    
     SELECT SEQ_EMPNO.NEXTVAL FROM DUAL;
  
  --========================
  --시퀀스 변경
    
  ALTER SEQUENCE SEQ_EMPNO
  INCREMENT BY 10
  MAXVALUE 400; 
  
  
   SELECT SEQ_EMPNO.NEXTVAL FROM DUAL;
    SELECT SEQ_EMPNO.NEXTVAL FROM DUAL;
     SELECT SEQ_EMPNO.NEXTVAL FROM DUAL;
      SELECT SEQ_EMPNO.CURRVAL FROM DUAL;
      
 --= ============================
 --시퀀스 삭제
 
 DROP SEQUENCE SEQ_EMPNO;
 
 SELECT * FROM USER_SEQUENCES; 
 
 --========================
 
 

  
CREATE SEQUENCE SEQ_TEST5;

CREATE SEQUENCE SEQ_ENO
START WITH 300
INCREMENT BY 1
MAXVALUE 600
NOCYCLE
NOCACHE;


 SELECT SEQ_ENO.CURRVAL FROM DUAL;
   SELECT SEQ_ENO.NEXTVAL FROM DUAL;
   
   
-- 데이터 추가시 사용 -> 직원번호 컬럼에 사용
INSERT INTO EMPLOYEE (EMP_ID, EMP_NAME,EMP_NO, JOB_CODE, HIRE_DATE)
                          VALUES (SEQ_ENO.NEXTVAL, '김채힁' , ' 971230-200000', 'J6', SYSDATE);
                          
                          
                          
SELECT * FROM EMPLOYEE;
