-- ** KH 연습문제 **
-- 1. 각 부서별 사원 수를 조회
SELECT DEPT_CODE, COUNT(*) AS "사원수"
FROM EMPLOYEE
GROUP BY DEPT_CODE
ORDER BY 1;

-- 2. 각 직급별 총 급여 합계 조회
 SELECT JOB_CODE, SUM(SALARY)
 FROM EMPLOYEE
 GROUP BY JOB_CODE
 ORDER BY 2 DESC;
 
-- 3. 각 부서별 평균 급여 조회
SELECT DEPT_CODE, FLOOR(AVG(SALARY)) "평균급여"
FROM EMPLOYEE
GROUP BY DEPT_CODE
ORDER BY 2 DESC;

-- 4. 부서 평균 급여가 300만원 이상인 부서 정보 조회 (부서코드, 평균 급여)
SELECT DEPT_CODE, FLOOR(AVG(SALARY)) "평균급여"
FROM EMPLOYEE
GROUP BY DEPT_CODE
HAVING FLOOR (AVG(SALARY)) >=3000000
ORDER BY 2 DESC;

-- 5. 2000년 1월 1일 이후 입사한 사원들을 대상으로 각 부서별 사원 수 조회
SELECT DEPT_CODE, COUNT(*) AS "사원수"
FROM EMPLOYEE
WHERE HIRE_DATE >= TO_DATE ('2000-01-01' , 'YYYY-MM-DD')
GROUP BY DEPT_CODE
ORDER BY 1;


-- 6. 부서별 최고 급여가 400만원 이상인 부서 정보 조회
SELECT DEPT_CODE, MAX(SALARY) AS "최고급여"
FROM EMPLOYEE
GROUP BY DEPT_CODE
HAVING  MAX(SALARY) >= 4000000;


-- 7. 각 사수별 관리 중인 사원 수 조회 (* 사수번호: MANAGER_ID)
SELECT MANAGER_ID, COUNT(*) AS "관리사원수"
FROM EMPLOYEE
WHERE MANAGER_ID IS NOT NULL
GROUP BY MANAGER_ID;

-- * KH 실습 문제 (4)* --
-- 1. 인사관리부 부서의 사원들의 사번, 사원명, 보너스 조회
--- > 사원 (EMPLOYEE), 부서(DEPARTMENT)
-- * 오라클 구문 * --
SELECT EMP_ID, EMP_NAME, BONUS
FROM  EMPLOYEE E, DEPARTMENT D
WHERE E.DEPT_CODE = D.DEPT_ID
AND D.DEPT_TITLE = '인사관리부'; 

         
-- * ANSI 구문 * --
SELECT EMP_ID, EMP_NAME, BONUS
FROM EMPLOYEE 
JOIN DEPARTMENT 
ON DEPT_CODE = DEPT_ID
WHERE DEPT_TITLE = '인사관리부'; 



-- 2. 전체 부서의 부서코드, 부서명, 지역코드, 지역명 조회
-- * 부서(DEPARTMENT), 지역(LOCATION)
-- * 오라클 구문 * --
SELECT DEPT_ID, DEPT_TITLE, LOCAL_CODE, LOCAL_NAME
FROM DEPARTMENT , LOCATION 
WHERE LOCATION_ID = LOCAL_CODE;

-- * ANSI 구문 * --
SELECT DEPT_ID, DEPT_TITLE, LOCAL_CODE, LOCAL_NAME
FROM DEPARTMENT 
JOIN LOCATION 
ON LOCATION_ID = LOCAL_CODE;


-- 3. 보너스를 받는 사원의 사번, 사원명, 보너스, 부서명 조회
-- * 사원(EMPLOYEE), 부서(DEPARTMENT)
-- * 오라클 구문 * --
SELECT EMP_ID, EMP_NAME, BONUS, DEPT_TITLE
FROM EMPLOYEE , DEPARTMENT 
WHERE DEPT_CODE = DEPT_ID
AND BONUS IS NOT NULL;


-- * ANSI 구문 * --
SELECT EMP_ID, EMP_NAME, BONUS, DEPT_TITLE
FROM EMPLOYEE 
JOIN DEPARTMENT 
ON DEPT_CODE = DEPT_ID
WHERE BONUS IS NOT NULL;


-- 4. 총무부가 아닌 사원들의 사원명, 급여 조회
-- * 사원(EMPLOYEE), 부서(DEPARTMENT)
-- * 오라클 구문 * --
SELECT EMP_NAME, SALARY 
FROM EMPLOYEE , DEPARTMENT  
WHERE  DEPT_CODE = DEPT_ID
AND DEPT_TITLE <>  '총무부';

-- * ANSI 구문 * --
SELECT EMP_NAME, SALARY 
FROM EMPLOYEE 
JOIN DEPARTMENT 
ON DEPT_CODE = DEPT_ID
WHERE DEPT_TITLE <>  '총무부';



-- 5. 사번, 사원명, 부서명, 지역명, 국가명 조회
--- * 사원(employee), 부서(DEPARTMENT), 지역(LOCATION), 국가(NATIONAL)
-- ** 오라클 구문 ** --
SELECT EMP_ID, EMP_NAME, DEPT_TITLE, LOCAL_CODE, NATIONAL_NAME
FROM EMPLOYEE, DEPARTMENT, LOCATION, NATIONAL
WHERE DEPT_CODE = DEPT_ID         -- 조인 조건 : EMPLOYEE +  DEPARTMENT
AND LOCATION_ID = LOCAL_CODE  -- 조인 조건 : DEPARTMENT + LOCATION
AND LOCATION.NATIONAL_CODE = NATIONAL.NATIONAL_CODE;

-- ** ANSI 구문 ** --
SELECT EMP_NO, EMP_NAME, DEPT_TITLE, LOCAL_NAME, NATIONAL_CODE
FROM EMPLOYEE 
JOIN DEPARTMENT
ON DEPT_CODE = DEPT_ID       
JOIN LOCATION ON LOCATION_ID = LOCAL_CODE  
JOIN NATIONAL USING (NATIONAL_CODE);


-- 6. 사번, 사원명, 부서명, 직급명, 지역명, 국가명, 급여등급 조회
-- * 사원(EMPLOYEE), 부서(DEPARTMENT), 직급(JOB), 지역(LOCATION), 국가(NATIONAL), 급여등급(SAL_GRADE)
-- ** 오라클 구문 ** --
SELECT EMP_ID, EMP_NAME, DEPT_TITLE, JOB_NAME, LOCAL_NAME, NATIONAL_NAME, SAL_LEVEL
FROM EMPLOYEE E, DEPARTMENT, JOB J, LOCATION L, NATIONAL N, SAL_GRADE
WHERE DEPT_CODE = DEPT_ID
AND E.JOB_CODE = J.JOB_CODE 
AND LOCATION_ID = LOCAL_CODE
AND L.NATIONAL_CODE = N.NATIONAL_CODE
AND SALARY BETWEEN MIN_SAL AND MAX_SAL; 

-- ** ANSI 구문 ** --

SELECT EMP_ID, EMP_NAME, DEPT_TITLE, JOB_NAME, LOCAL_NAME, NATIONAL_NAME, SAL_LEVEL
FROM EMPLOYEE 
JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID
JOIN  JOB USING (JOB_CODE) 
JOIN LOCATION ON LOCATION_ID = LOCAL_CODE
JOIN NATIONAL USING (NATIONAL_CODE)
JOIN  SAL_GRADE ON SALARY BETWEEN MIN_SAL AND MAX_SAL;






